services:
  mariadb:
    build: ./requirements/mariadb
    container_name:
      mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file: 
      - .env
    volumes:
      - db-volume:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name:
      nginx
    env_file: 
      - .env  
    networks:
      - inception
    ports:
      - "443:443"
  wordpress:
    build: ./requirements/wordpress
    container_name:
      wordpress
    depends_on:
      - mariadb
      - nginx
    networks:
      - inception
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/bcarolle/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/bcarolle/data/mariadb

networks:
    inception:
        driver: bridge
