services:
  mariadb:
    build: ./requirements/mariadb
    container_name:
      mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file: 
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name:
      nginx
    env_file: 
      - .env  
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name:
      wordpress
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/wordpress
    restart: always
  redis:
    build: ./requirements/redis
    container_name:
      redis
    networks:
      - inception
    ports:
      - "6379:6379"
    restart: always
  proftpd:
    build: ./requirements/proftpd
    container_name:
      proftpd
    networks:
      - inception
    ports:
      - "21:21"
      - "49152-49182:49152-49182"
    volumes:
      - wp-volume:/var/www/wordpress
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/bcarolle/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/bcarolle/data/mariadb

networks:
    inception:
        driver: bridge
