version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name:
      mariadb
    networks:
      - network
    ports:
      - "3306:3306"
    env_file: ".env"
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name:
      nginx
    depends_on:
      - wordpress
    networks:
      - network
    ports:
      - "443:443"
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name:
      wordpress
    depends_on:
      - mariadb
    networks:
      - network
    ports:
      - "9000:9000"
    env_file: ".env"
    restart: always

networks:
  network:
